sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov

deploy:
  provider: heroku
  api_key: ab96e7e4-7e36-4133-8837-3714be7a0d48
  app: openclub-web

notifications:
  slack: openclub:1W4Wix44Cr3AHWfkdx0ALrHs
